### ISSUE TITLE
Changing or Adding Keybinds

### ISSUE THREAD

**Issue by p51douglas** [Toludin/LunarSphere#1]
Date: 2018-07-18 13:03:55
ID: 21
Error occured in: Global
Count: 1
Message: ..\AddOns\LunarSphere\lib\moduleSettings.lua line 4553:
   attempt to index a nil value
Debug:
   LunarSphere\lib\moduleSettings.lua:4553: StanceIconSetup()
   LunarSphere\lib\moduleSettings.lua:4040:
      LunarSphere\lib\moduleSettings.lua:3914
   [C]: Show()
   LunarSphere\lib\moduleButton.lua:1859:
      LunarSphere\lib\moduleButton.lua:1792
Locals:
self = <table> {
 ButtonDialog = LSButtonDialog {
 }
 AnchorRadio_OnClick = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:6204
 Keybind_OnKeyUp = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4646
 WipeTemplateHandler = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5767
 BuildTemplateList = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5817
 SpeechList_OnLeave = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5159
 UpdateGaugeOptions = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4789
 templateList = <table> {
 }
 UpdateMainButtons = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4419
 ReagentList_OnReceiveDrag = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5352
 Frame = LSSettings {
 }
 SetEnabled = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4434
 MenuDropdownInitialize = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4581
 ResetSpeechObjects = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5163
 ButtonVisibilityFunction = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4633
 ReagentList_OnTextChanged = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5335
 TemplateHandlerDialog = LSTemplateHandlerDialog {
 }
 List_OnLeave = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4460
 UpdateMemoryReloadButton = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4857
 TemplateList_OnClick = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5776
 SpeechList_OnEnter = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5150
 UpdateSpeechList = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5198
 StanceIcon_Click = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4247
 ActionList_AddAction = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4874
 StanceIcon_Leave = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4239
 AnchorOrRadio_OnDragStop = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:6186
 ActionList_OnDragOrClick = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4998
 AnchorRadio_OnDragStart = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:6182
 SetUseButtonMenuValue = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4482
 ShowCountFunction = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4470
 GetChannelText = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5104
 ImportArtDialog = LSImportArtDialog {
 }
 memoryEdit = <table> {
 }
 buttonEdit = 1
 buttonEditCache = <table> {
 }
 version = 1.3
 UpdateSkinOptions = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:6137
 ActionList_PrepareAction = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4950
 AddToRepairLog = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5493
 EnableHideUI = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:6325
 UpdateTemplateList = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5854
 ShowCooldownFunction = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4476
 SetMemoryValue = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4783
 ToggleSettingsFrame = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4224
 AnchorButton_OnClick = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:6178
 ReagentList_OnEnter = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:5339
 ActionList_ClearActionObjects = <function> defined @Interface\AddOns\LunarSphere\lib\moduleSettings.lua:4940
 Updat
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  NPCScanOverlay, v7.3.0.1
  NPCScanOverlayBroker, v1.2.7
  Ace3, v
  ACP, vr257 
  Altoholic, vr183
  AskMrRobot, v59
  Babylonian, v5.1.DEV.332(/embedded)
  Configator, v5.1.DEV.431(/embedded)
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v8.0.0
  DBMDefaultSkin, v
  DBMGUI, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.75
  ElvUIConfig, v1.05
  Gatherer, v7.3.1
  GatherMate2, v1.42
  GTFO, v4.46
  HandyNotes, vv1.5.2
  HandyNotesAchievements, v0.4.19
  HandyNotesAzerothsTopTunes, vv1.2.1
  HandyNotesBrokenShore, vv1.24
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.32
  HandyNotesEliteBattlePets, v1
  HandyNotesEphemeralCrystals, vr01
  HandyNotesHigherDimensionalLearning, v1
  HandyNotesHigherLearning, v7.3.5.0
  HandyNotesKosumoth, v1
  HandyNotesLegionInstanceWorldQuests, vv1.12
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTownPortals, v0.0.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesLunarFestival, vv1.4.5
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSpecialNPCsEtc, v1.1.1-Beta
  HandyNotesSummerFestival, vv1.4.2
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarShalAranTelemancy, vv1.16
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.18
  HandyNotesTimelessTreasures, v1.0.7
  HandyNotesTravelGuide, vv1.9.2
  HandyNotesTreasureHunter, v1
  HandyNotesWellRead, v7.3.5.0
  HandyNotesWitheredArmyTraining, v1
  HandyNotesWitheredChests, v1.2
  HeroCache, v8.0.1.00
  HeroLib, v8.0.1.00
  HeroRotation, v8.0.1.00
  HeroRotationRogue, v
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LunarSphere, vv1.30
  MikScrollingBattleText, v5.7.148
  NPCScan, v8.0.1.1
  OmniCC, v7.3.1
  OPie, vVanilla 5
  Overachiever, v1.0.0
  Pawn, v2.2.20
  Postal, vv3.5.9
  SexyMap, vv8.0.1
  Simulationcraft, v1.10.1
  SlideBar, v7.3.1 (<%codename%>)
  WeakAuras, v2.6.0
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=b08)

**Comment by Toludin** [comment]
Should be fixed - give the latest version a try and let me know if it's still a problem. Also let me know which class you're on and what buttons you press/what you try to do when this happens if possible. Thanks!

**Comment by p51douglas** [comment]
I was on rogue, starting from scratch. You get a sphere with blank buttons. When I attempted to use stances and add spells to the buttons, it resulted in that error. The intended functionality of stances is where LS dynamically changes its buttons to different ones if you are in stealth or not.
I am pleased to report that your update has apparently solved the problem. I will test more on different toons but as of now LS is working as intended. Very nice job!

**Comment by Toludin** [comment]
Awesome, glad to hear. Yea, from what I saw it looked like Druid and Rogue were going to run into the issue you did, I just hadn't tested it with either class. Glad to hear it's working for you - thanks for testing!
