### ISSUE TITLE
Attempting to add WarMode PVP Spells to Buttons

### ISSUE THREAD

**Issue by p51douglas** [Toludin/LunarSphere#2]
Date: 2018-07-19 10:34:06
ID: 20
Error occured in: Global
Count: 1
Message: ..\AddOns\LunarSphere\lib\moduleObject.lua line 1060:
   attempt to concatenate local 'spellRank' (a nil value)
Debug:
   LunarSphere\lib\moduleObject.lua:1060:
      LunarSphere\lib\moduleObject.lua:991
Locals:
self = LSSettingsbuttonAction1 {
 0 = <userdata>
 HotKey = LSSettingsbuttonAction1HotKey {
 }
 NewActionTexture = <unnamed> {
 }
 Border = LSSettingsbuttonAction1Border {
 }
 Flash = LSSettingsbuttonAction1Flash {
 }
 icon = LSSettingsbuttonAction1Icon {
 }
 AutoCastable = <unnamed> {
 }
 SpellHighlightAnim = <unnamed> {
 }
 SpellHighlightTexture = <unnamed> {
 }
 NormalTexture = LSSettingsbuttonAction1NormalTexture {
 }
 FlyoutBorderShadow = LSSettingsbuttonAction1FlyoutBorderShadow {
 }
 FlyoutBorder = LSSettingsbuttonAction1FlyoutBorder {
 }
 Count = LSSettingsbuttonAction1Count {
 }
 AutoCastShine = LSSettingsbuttonAction1Shine {
 }
 FlyoutArrow = LSSettingsbuttonAction1FlyoutArrow {
 }
 cooldown = LSSettingsbuttonAction1Cooldown {
 }
 Name = LSSettingsbuttonAction1Name {
 }
}
objectTexture = nil
objectType = nil
actionName = nil
objectName = "button"
buttonID = 3
currentStance = 0
updateType = "spell"
updateID = 0
updateData = "spell"
useCached = true
buttonType = 1
clickType = 1
typeName = "None"
nextSpellName = nil
spellRank = nil
spellName = nil
spellID = nil
(*temporary) = "("
(*temporary) = nil
(*temporary) = ")"
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'spellRank' (a nil value)"

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  NPCScanOverlay, v7.3.0.1
  NPCScanOverlayBroker, v1.2.7
  Ace3, v
  ACP, vr257 
  AskMrRobot, v59
  Babylonian, v5.1.DEV.332(/embedded)
  Configator, v5.1.DEV.431(/embedded)
  DBMCore, v8.0.0
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.75
  ElvUIConfig, v1.05
  Gatherer, v7.3.1
  GatherMate2, v1.42
  GTFO, v4.46
  HandyNotes, vv1.5.2
  HandyNotesAchievements, v0.4.19
  HandyNotesAzerothsTopTunes, vv1.2.1
  HandyNotesBrokenShore, vv1.24
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.32
  HandyNotesEliteBattlePets, v1
  HandyNotesEphemeralCrystals, vr01
  HandyNotesHigherDimensionalLearning, v1
  HandyNotesHigherLearning, v7.3.5.0
  HandyNotesKosumoth, v1
  HandyNotesLegionInstanceWorldQuests, vv1.12
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTownPortals, v0.0.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesLunarFestival, vv1.4.5
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSpecialNPCsEtc, v1.1.1-Beta
  HandyNotesSummerFestival, vv1.4.2
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarShalAranTelemancy, vv1.16
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.18
  HandyNotesTimelessTreasures, v1.0.7
  HandyNotesTravelGuide, vv1.9.2
  HandyNotesTreasureHunter, v1
  HandyNotesWellRead, v7.3.5.0
  HandyNotesWitheredArmyTraining, v1
  HandyNotesWitheredChests, v1.2
  HeroCache, v8.0.1.00
  HeroLib, v8.0.1.00
  HeroRotation, v8.0.1.00
  HeroRotationPaladin, v
  LunarSphere, vv1.30
  MikScrollingBattleText, v5.7.148
  NPCScan, v8.0.1.1
  OmniCC, v7.3.1
  OPie, vVanilla 5
  Overachiever, v1.0.0
  Pawn, v2.2.20
  Postal, vv3.5.9
  SexyMap, vv8.0.1
  Simulationcraft, v1.10.1
  SlideBar, v7.3.1 (<%codename%>)
  VuhDo, v3.93
  VuhDoOptions, v3.93
  WeakAuras, v2.6.0
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=92a)

**Comment by Toludin** [comment]
Thanks! Should be fixed now.
